=== gocko/SSQSA-COP/XML/Clones/XMLSchema.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:complexType name="function">

		<xs:sequence>
			<xs:element name="FQN" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="File" type="xs:string"></xs:element>
			<xs:element name="Name" type="xs:string"></xs:element>
			<xs:element name="Type" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Clone">   
		<xs:sequence>          				
			<xs:element name="function" type="function"/>   
			<xs:element name="From_line" type="xs:int"/>
			<xs:element name="To_line" type="xs:int"/> 
		</xs:sequence>     
   	</xs:complexType>
    
	<xs:complexType name="Clones">  		
			<xs:sequence>        
				<xs:element name="similarity" type="xs:double"/>   				
				<xs:element name="clone" type="Clone" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>  
	</xs:complexType>



	<xs:element name="clones" type="Clones"></xs:element>
</xs:schema>

=== gocko/SSQSA-COP/XML/Changes/ClonesFromSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<clones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchema.xsd">
  <similarity>0.0</similarity>
  <clone>
    <function>
      <FQN>FQN</FQN>
      <File>File</File>
      <Name>Name</Name>
      <Type>Type</Type>
    </function>
    <From_line>From_line</From_line>
    <To_line>To_line</To_line>
  </clone>
</clones>
