=== gocko/SSQSA-COP/XML/Metrics/XMLSchema.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="component" type="Component"/>     
  
  <xs:complexType name="Metrics">
                  <xs:sequence>
                  	<xs:element name="CC" type="xs:integer" />
                  	<xs:element name="LOC" type="xs:integer" />
                  	<xs:element name="NOP" type="xs:integer" />
                  	<xs:element name="NOC" type="xs:integer" />
                  	<xs:element name="DIT" type="xs:integer" />
                  	<xs:element name="NOCH" type="xs:integer" />
                  	<xs:element name="CBO" type="xs:integer" />
                  	<xs:element name="Halstead" type="Halstead"></xs:element>
                  </xs:sequence>
  </xs:complexType>
    <xs:complexType name="Component">
      <xs:sequence>
        <xs:element name="entity" type="Entity" maxOccurs="unbounded"/>  
       </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Entity">
    	<xs:sequence>
        	<xs:element name="name" type="xs:string"/>
              <xs:element name="FQN" type="xs:string"/>
              <xs:element name="metrics" type="Metrics"/>               
            </xs:sequence>
        <xs:attribute type="xs:string" name="type" use="required"/>
    </xs:complexType>


    <xs:complexType name="Halstead">
    	<xs:attribute name="n1" type="xs:int"></xs:attribute>
    	<xs:attribute name="n2" type="xs:int"></xs:attribute>
    	<xs:attribute name="N1" type="xs:int"></xs:attribute>
    	<xs:attribute name="N2" type="xs:int"></xs:attribute>
    	<xs:attribute name="n" type="xs:int"></xs:attribute>
    	<xs:attribute name="N" type="xs:int"></xs:attribute>
    	<xs:attribute name="Volume" type="xs:float"></xs:attribute>
    	<xs:attribute name="Level" type="xs:float"></xs:attribute>
    	<xs:attribute name="Difficulty" type="xs:float"></xs:attribute>
    	<xs:attribute name="Effort" type="xs:float"></xs:attribute>
    	<xs:attribute name="Time" type="xs:float"></xs:attribute>
    	<xs:attribute name="Inteligence" type="xs:float"></xs:attribute>
    	
    	
    </xs:complexType>
</xs:schema>

=== gocko/SSQSA-COP/XML/Metrics/MetricsFromSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchema.xsd">
  <entity type="">
    <name>name</name>
    <FQN>FQN</FQN>
    <metrics>
      <CC>0</CC>
      <LOC>0</LOC>
      <NOP>0</NOP>
      <NOC>0</NOC>
      <DIT>0</DIT>
      <NOCH>0</NOCH>
      <CBO>0</CBO>
      <Halstead Difficulty="0.0" Effort="0.0" Inteligence="0.0" Level="0.0" N="0" N1="0" N2="0" Time="0.0" Volume="0.0" n="0" n1="0" n2="0"/>
    </metrics>
  </entity>
</component>
